#!/bin/env bash
# Bash script to display "Best School" 10 times, with "Hi" on a new line during the 9th iteration

num=1

while [ $num -lt 10 ]
do
  if [ $num -eq 9 ]
  then
    echo "Hi"
  fi
    echo "Best School"
    (( num++ ))
done
