#!/bin/env bash
# Bash script to display "Best School" 10 times, with "Hi" on a new line during the 9th iteration

num=1

while [ $num -le 10 ]
do
  if [ $num -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  
  ((num++))
done
